import Head from "next/head";
import Link from "next/link";
import Category from "../components/common/Category";
import useSWR from "swr";
import fetcher from "../lib/fetcher";
import Product from "../components/common/ProductCard";
import Loader from "../components/common/Loader";

export default function Home() {
  const { data, error, isLoading } = useSWR(
    "https://fakestoreapi.com/products?limit=8",
    fetcher
  );
  console.log(data);

  return (
    <>
      <Head>
        <title>E-store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="md:flex gap-4 mt-12">
        <Category />

        <div className="w-full">
          <div className="hero-section hs-2 my-8 shadow rounded-md py-16 md:py-24 px-4 bg-[#cc0023] text-white">
            <h2 className="font-bolder md:text-5xl text-4xl">
              <span className="bg-slate-50-300">WINTER</span> IS
              <br /> <del className="DEL">COMING</del> HERE.
            </h2>
          </div>
          <div className="hero-section hs-1 my-8 shadow rounded-md py-16 md:py-24 px-4 bg-slate-100 text-right">
            <h2 className="font-bolder md:text-5xl text-4xl">
              LET'S EXPLORE <br />
              <span className="bg-yellow-300">UNIQUE</span> <br /> CLOTHES.
            </h2>
          </div>

          <h2 className="text-3xl md:text-4xl font-bold mt-16 mb-8">
            🔥 Hot sale
          </h2>
          <div className="p-4">
            <div className="sm:block lg:flex items-center border shadow rounded-md justify-between w-full">
              <img
                src="/assets/shoe.png"
                alt="Shoe"
                className="w-full sm:max-w-[300px] lg:max-w-[500px] mx-auto"
              />
              <div className="py-8 px-4 flex-auto mx-auto lg:text-left text-center">
                <h2 className="font-bold text-lg py-3"> Nike Air Jordan </h2>
                <p className="py-1"> Shoes </p>
                <p className="pt-1 font-bold"> BDT: 800 </p>
                <p>
                  <del>BDT: 1500</del> &nbsp; -
                  {Math.round(((1500 - 800) * 100) / 1500)}%
                </p>
                <button className="px-2 py-4 rounded-md shadow my-8 bg-yellow-300 font-bold">
                  Buy Now
                </button>
              </div>
            </div>
          </div>

          <div className="my-12">
            <h2 className="text-3xl md:text-4xl font-bold mt-16 mb-8">
              💖 Popular
            </h2>
            <div className="text-center">{isLoading ? <Loader /> : ""}</div>
            <div className="w-full py-8 grid gap-4 lg:grid-cols-3 sm:grid-cols-2 grid-cols-1">
              {data?.map((product: any) => (
                <Product
                  key={product.title + product.id}
                  name={product.title}
                  category={product.category}
                  image={product.image}
                  price={product.price}
                  rating={product.rating.rate}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
